image: mcr.microsoft.com/dotnet/core/sdk:3.1.300

deploy:
  image: docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  before_script:
    - 'cd src/Food.Web.Host'
    - chmod -R a+x ./docker-publish.sh
  script:
    - ./docker-publish.sh
  only:
    - master
